language: objective-c
osx_image: xcode11.5
before_install:
- gem install slather -N 

script: 
-xctool -project libPhoneNumber.xcodeproj -scheme libPhoneNumberiOS build -scheme libPhoneNumberiOSTests test -sdk iphonesimulator
-xctool -project libPhoneNumber.xcodeproj -scheme libPhoneNumberGeocoding build -scheme libPhoneNumberGeocodingTests test -sdk iphonesimulator
-xctool -project libPhoneNumber.xcodeproj -scheme libPhoneNumberShortNumber build -scheme libPhoneNumberShortNumberTests test -sdk iphonesimulator

after_success: slather 
