language: objective-c
osx_image: xcode11.5
before_install:
- gem install slather -N 

script:
- xcodebuild -project libPhoneNumber.xcodeproj -scheme libPhoneNumberiOSTests clean
- xcodebuild -project libPhoneNumber.xcodeproj -scheme libPhoneNumberiOSTests -sdk iphonesimulator13.5 -configuration Debug build test

- xcodebuild -project libPhoneNumber.xcodeproj -scheme libPhoneNumberGeocodingTests -sdk iphonesimulator13.5 -configuration Debug build test

- xcodebuild -project libPhoneNumber.xcodeproj -scheme libPhoneNumberShortNumberTests -sdk iphonesimulator13.5 -configuration Debug build test

after_success: slather 
