language: objective-c
osx_image: xcode11.5
before_install:
- gem install slather -N 

script: 

-xcodebuild -project libPhoneNumber.xcodeproj -scheme libPhoneNumberiOSTests -sdk iphonesimulator10.3 -destination 'platform=iOS Simulator,OS=13.5,name=iPhone X' -configuration Debug build test
-xcodebuild -project libPhoneNumber.xcodeproj -scheme libPhoneNumberGeocodingTests -sdk iphonesimulator10.3 -destination 'platform=iOS Simulator,OS=13.5,name=iPhone X' -configuration Debug build test
-xcodebuild -project libPhoneNumber.xcodeproj -scheme libPhoneNumberShortNumberTests -sdk iphonesimulator10.3 -destination 'platform=iOS Simulator,OS=13.5,name=iPhone X' -configuration Debug build test

after_success: slather 
