language: objective-c

before_install:
- gem install slather -N 

script:

- xcodebuild test -project libPhoneNumber.xcodeproj -scheme libPhoneNumberiOSTests -destination "platform=iOS Simulator,name=iPhone X" -sdk iphonesimulator11 CODE_SIGNING_REQUIRED=NO
- xcodebuild test -project libPhoneNumber.xcodeproj -scheme libPhoneNumberGeocodingTests -destination "platform=iOS Simulator,name=iPhone X" -sdk iphonesimulator11 CODE_SIGNING_REQUIRED=NO
- xcodebuild test -project libPhoneNumber.xcodeproj -scheme libPhoneNumberShortNumberTests -destination "platform=iOS Simulator,name=iPhone X" -sdk iphonesimulator11 CODE_SIGNING_REQUIRED=NO

after_success: slather 
