language: objective-c
osx_image: xcode11.5	
before_install:
- gem install slather -N 

script:

- xcodebuild test -project libPhoneNumber.xcodeproj -scheme libPhoneNumberiOSTests -destination "platform=iOS Simulator,name=iPhone 11" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO
- xcodebuild test -project libPhoneNumber.xcodeproj -scheme libPhoneNumberGeocodingTests -destination "platform=iOS Simulator,name=iPhone 11" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO
- xcodebuild test -project libPhoneNumber.xcodeproj -scheme libPhoneNumberShortNumberTests -destination "platform=iOS Simulator,name=iPhone 11" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO
- swift test -c release

after_success: slather 
