language: objective-c

before_install:
- gem install slather -N 

script:

xctool -project libPhoneNumber.xcodeproj -scheme libPhoneNumberiOS build -scheme libPhoneNumberiOSTests test -sdk iphonesimulator


after_success: slather 
